project:
  type: website
  output-dir: docs 

website:
  title: "EpiPulse"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: public_health_data_analaysis.qmd
        text: Public Health Data Analysis
      
format:
  html:
    theme:
      light: [flatly, publichealth.scss]
    toc: true
    number-sections: true

