project:
  type: website
  output-dir: docs

website:
  title: "EpiPulse"
  page-navigation: true
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: programs.qmd
        text: Programs
      - href: impact.qmd
        text: Impact
      - href: public_health_data_analysis.qmd
        text: Resources
      - href: ai_with_r.qmd
        text: AI With R
      - href: community.qmd
        text: Community
      - href: contact.qmd
        text: Contact
    right:
      - href: transparency.qmd#donation-and-payment-status
        text: Support Us
  page-footer:
    left: "EpiPulse | Evidence to Action in Public Health"
    right:
      - href: transparency.qmd
        text: Transparency
      - href: community.qmd
        text: Community
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      - litera
      - publichealth.scss
    toc: true
    number-sections: false
    smooth-scroll: true

