project:
  type: website
  output-dir: docs 

website:
  title: "Epipulse public health data analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cleaning_validation.qmd
        text: Cleaning and validation


format:
  html:
    toc: true
    number-sections: true
